### ISSUE TITLE
tracker: system optimization

### ISSUE THREAD

**Issue by iaacornus** [iaacornus/Fedora-OSTree-Setup#11]
tasks were removed to avoid confusion in trackers

log: 02/03/23 3:54AM UTC+8:00

**Comment by trytomakeyouprivate** [comment]
what are these? I am interested. Are startups set after installing apps? then that would have to be part of the startup script right?

**Comment by iaacornus** [comment]
> what are these? I am interested. 

it's for removing of preinstalled apps and disabling of some apps from autostart like gnome-software.

**Comment by iaacornus** [comment]
baloo is removed since in kinoite its either not there or not negligible based in my experience.

**Comment by iaacornus** [comment]
merged with #38 and #41

**Comment by trytomakeyouprivate** [comment]
how to remove baloo? It is a core dependency for Dolphin to work somehow. You can disable it in the settings though.

**Comment by iaacornus** [comment]
> how to remove baloo? It is a core dependency for Dolphin to work somehow. You can disable it in the settings though.

it will simply be disabled like gnome-software

**Comment by trytomakeyouprivate** [comment]
balooctl disable && balooctl purge
