### ISSUE TITLE
Setup Gnome Boxes

### ISSUE THREAD

**Issue by trytomakeyouprivate** [iaacornus/Fedora-OSTree-Setup#21]
Boxen performs way better than Virtualbox, which is also hard to setup on fedora. The flatpak version has some problems, making it not very usable.

https://dausruddin.com/how-to-enable-clipboard-and-folder-sharing-in-qemu-kvm-on-windows-guest/

```
sudo rpm-ostree install gnome-boxes virt-manager #decide what to use

# Clipboard sharing
wget https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe -P ~/Downloads/

zenity --info --text=" \n "Spice-Guest-Addition" was downloaded.  \n Please move it to a USB-Stick, import it to your Windows-VM \n and install it there. Your Display may blink for a short time. " --title="Enabling Clipboard-Sync"

#Folder sharing with Cockpit ?

sudo rpm-ostree install cockpit
sudo systemctl enable --now cockpit.socket
sudo firewall-cmd --add-service=cockpit
sudo firewall-cmd --add-service=cockpit --permanent

xdg-open http://localhost:9090/ 

xdg-open https://dausruddin.com/how-to-enable-clipboard-and-folder-sharing-in-qemu-kvm-on-windows-guest/

wget https://www.spice-space.org/download/windows/spice-webdavd/spice-webdavd-x64-latest.msi -P ~/Downloads

wget https://www.spice-space.org/download/windows/spice-webdavd/spice-webdavd-x86-latest.msi -P ~/Downloads/

zenity --info --text="Please follow the tutorial on this site. \n Downloads should be already done to your Downloads directory." --title="Enabling Folder-Sync.  \n You will need a USB-Stick / SD Card / external Drive"

```

**Comment by iaacornus** [comment]
I'm not sure of all other processes, perhaps just make them optional since it can be too intruding when prompted to install a clipboard thingy, for example in my case I dont use windows and clipboard sync, what do you think?

**Comment by iaacornus** [comment]
also really seem excessive to me, it installs bunches of other stuff, and plugins and doesn't complete the task. Moreover, gnome boxes flatpak work most of the time and seem to be better solution than all these excessive modification

**Comment by trytomakeyouprivate** [comment]
I have to try the flatpak again, it didnt work for me. 

Sorry for not elaborating, these steps were only for running win10 in a vm. Which is, again, also pretty complicated.

Of course this will be optional

**Comment by trytomakeyouprivate** [comment]
So Gnome Boxes Flatpak doesnt allow USB devices, so there is no real way to make Windows work. This could be a dealbreaker for people needing windows in a VM

**Comment by iaacornus** [comment]
> So Gnome Boxes Flatpak doesnt allow USB devices, so there is no real way to make Windows work. This could be a dealbreaker for people needing windows in a VM

that's a fair point I say, yeah this should be included

**Comment by iaacornus** [comment]
seems like its already tracked in #38

**Comment by trytomakeyouprivate** [comment]
I switched to virt-manager and its way better in my experience. Would not advise Boxes anymore, it lacks features.

**Comment by iaacornus** [comment]
> I switched to virt-manager and its way better in my experience. Would not advise Boxes anymore, it lacks features.

agreed about this, but this one should be layered right? I have not used this one, so i'm not sure if this would work in toolbox or something, this seems a better alternative

**Comment by trytomakeyouprivate** [comment]
The silverblue devs think about preinstalling gnome-boxes, which I would then just remove and install virt-manager on the system instead. Its just way better.

Yes I also didnt try to run it in a podman container, I think that would be a mess.
