### ISSUE TITLE
Flatpak purge removed files

### ISSUE THREAD

**Issue by trytomakeyouprivate** [iaacornus/Fedora-OSTree-Setup#28]
its soo annoying, that the Flatpak CLI doesnt remove leftover files.

[Here is a bash script offering deletion of Flatpak directories with no corresponding app existing](https://raw.githubusercontent.com/ChristianSilvermoon/Flatpurge/master/flatpurge)

I think we should add that and create an appstarter for it.

```
wget https://raw.githubusercontent.com/ChristianSilvermoon/Flatpurge/master/flatpurge -P ~/.scripts

chmod +x  ~/.scripts/*
```

I cant get an appstarter to open a GUI Terminal and allow interaction.

the command would be `~/.scripts/flatpurge -d`

**Comment by iaacornus** [comment]
doesn't `flatpak --delete-data` option removes it?

**Comment by iaacornus** [comment]
from the script it just deletes `$HOME/.var/app/flatpakapp` which seems to be handled by `--delete-data` option when called in `flatpak uninstall`

**Comment by iaacornus** [comment]
i've reviewed the script, it just seems an implementation of `--delete-data`:

```bash
appdir="$HOME/.var/app"
...
purge_prompt() {
	if [ "${#N[@]}" = "0" ]; then
		echo "You have no left over app directories!"
		return
	fi
	
	local choice
	for app in ${N[@]}; do

		if [ "$ARG_FORCE" ]; then
			echo -e "\e[31;1mDELETING\e[37;22m residual user data for \e[1m$app\e[22m"
			#rm -rf -- "$appdir/$app"
		else
			echo -en "\e[31;1mDELETE\e[37;22m residual user data for \e[1m$app\e[22m ? (Y/N) "
				read -rsn1 choice
				echo ""
			if [ "${choice,,}" = "y" ]; then
				echo -e "\e[2mRemoving... \e[22m"
				rm -rf -- "$appdir/$app"
			fi
		fi
	done
}
...
```

so we really don't need it, we can just call `flatpak --system --delete-data $appname`, i'm closing this one

**Comment by trytomakeyouprivate** [comment]
ok found out about that too, good
