### ISSUE TITLE
System styling: KDE

### ISSUE THREAD

**Issue by trytomakeyouprivate** [iaacornus/Fedora-OSTree-Setup#31]
[This package](https://github.com/Lunarequest/sddm2rpm) to replace the SDDM theme manually. This is currently not possible.

Other problems:

- [x] unifying the breeze cursor (Brave, toolboxapps?)
- [ ] Installing Adapta Theme (optional)
- [ ] allow removing of old themes (currently not possible in GUI?)
- [ ] maybe change the font
- [ ] #55
- [ ] maybe add "Pixel perfect" icon theme, for HDPI screens
- [ ] remove the start screen? Makes system faster, ugly KDE loading stays anyways
- [x] #56

**Comment by trytomakeyouprivate** [comment]
For disabling the plopping sound, it is at `/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga` ,but read-only.

I can also not write in `/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/main.qml/` and comment out `property bool volumeFeedback: Plasmoid.configuration.volumeFeedback`

Its possible in the GUI somehow...

**Comment by iaacornus** [comment]
> For disabling the plopping sound, it is at `/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga` ,but read-only.
> 
> I can also not write in `/usr/share/plasma/plasmoids/org.kde.plasma.volume/contents/ui/main.qml/` and comment out `property bool volumeFeedback: Plasmoid.configuration.volumeFeedback`
> 
> Its possible in the GUI somehow...

the whole `/usr/` as well as other locations are user read-only, only `/etc/` and `/var`, as well as `/sys` can be tweaked as far as i know.

**Comment by iaacornus** [comment]
> [This package](https://github.com/Lunarequest/sddm2rpm) to replace the SDDM theme manually. This is currently not possible.
> 
> Other problems:
> 
>     * [ ]  unifying the breeze cursor (Brave, toolboxapps?)
> 
>     * [ ]  Installing Adapta Theme (optional)
> 
>     * [ ]  allow removing of old themes (currently not possible in GUI?)
> 
>     * [ ]  maybe change the font
> 
>     * [ ]  add MSFont (I can deal with that, as its problematic to host and Torrents are dead)
> 
>     * [ ]  maybe add "Pixel perfect" icon theme, for HDPI screens
> 
>     * [ ]  remove the start screen? Makes system faster, ugly KDE loading stays anyways
> 
>     * [ ]  Allow removing of start screens

aren't these, except point 1, excessive modifications tho? since shouldnt we leave appearance customization to user?

**Comment by trytomakeyouprivate** [comment]
SDDM styling: using layered "sddm2rpm" packages could this be possible

```
toolbox enter 
git clone https://github.com/Lunarequest/sddm2rpm.git
cargo install --path ~/sddm2rpm/
sddm2rpm
```

Question: all the needed packages for building rust are probably better off in a toolbox / distrobox right? The RPM can then be layered of course, to allow overwriting the SDDM theme.

**Comment by iaacornus** [comment]
> SDDM styling: using layered "sddm2rpm" packages could this be possible
> 
> ```
> toolbox enter 
> git clone https://github.com/Lunarequest/sddm2rpm.git
> cargo install --path ~/sddm2rpm/
> sddm2rpm
> ```
> 
> Question: all the needed packages for building rust are probably better off in a toolbox / distrobox right? The RPM can then be layered of course, to allow overwriting the SDDM theme.

not needed even toolbox is not, `cargo` install the packages somewhere in `$HOME` not in `/usr`. Then we can install the built `rpm` with `rpm-ostree`.

**Comment by iaacornus** [comment]
about 1, does the cursor in toolbox really different from the system? I've tried kinoite, but never noticed the difference of cursor in toolbox and system.

**Comment by trytomakeyouprivate** [comment]
this was only because cargo and dependencies are not preinstalled.

```
distrobox enter fedora --exec cargo add sddm2rpm

printf """
export PATH=/var/home/user/.cargo/bin/:$PATH""" >> ~/.bashrc
```

**Comment by trytomakeyouprivate** [comment]
kde team admitted the loading splash screen is useless and may be deactivated by default in the future. better would actually be to cover all the element loading and moving.

```
printf """[KSplash]
Engine=none
Theme=None""" > ~/.config/ksplashrc
```

This should work, its set like that when disabled.

**Comment by iaacornus** [comment]
> kde team admitted the loading splash screen is useless and may be deactivated by default in the future. better would actually be to cover all the element loading and moving.
> 
> ```
> printf """[KSplash]
> Engine=none
> Theme=None""" > ~/.config/ksplashrc
> ```
> 
> This should work, its set like that when disabled.

tracked in #47

**Comment by iaacornus** [comment]
addition of msfonts, removal of old themes, and removal of start screen options are good idea to me, rest are not really needed especiall adapta theme

**Comment by iaacornus** [comment]
already tracked in #38 , im closing this now
