### ISSUE TITLE
installation of third party repositories

### ISSUE THREAD

**Issue by iaacornus** [iaacornus/Fedora-OSTree-Setup#6]
- [ ] third party repository setups
    - [x] flathub
    - [x] gnome nightly
    - [x] kde nightly
    - [ ] rpmfusion
        - [x] free
        - [x] nonfree
        - [ ] tainted

**Comment by trytomakeyouprivate** [comment]
Testdisk COPR repo for new updates of testdisk:

sudo dnf copr enable grenier/testdisk
sudo dnf install testdisk qphotorec
