### ISSUE TITLE
How to sort issues?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [iaacornus/Fedora-OSTree-Setup#60]
I like your idea of the trackers. But how to use them? Do you have  new issue for ever sub-point and link it in the tracker?

**Comment by iaacornus** [comment]
> I like your idea of the trackers. But how to use them? Do you have new issue for ever sub-point and link it in the tracker?

its just to organize the issues based on what they are for, like

#16 is things that will be done after the initial reboot
#17 are things that is only for laptop
#38 are simple tweaks that only includes layering, changing of config, or overriding stuff
#41 are tweaks that involves changing base config 
#53 are for things that should be included in recommendations
