### ISSUE TITLE
libfprint setup (KDE only?)

### ISSUE THREAD

**Issue by trytomakeyouprivate** [iaacornus/Fedora-OSTree-Setup#63]
1. add fprint to install queue

2. add setup to reboot-script, including a notification and maybe invoked setup command

3. try on hardware (I have none, try how it reacts to login screen (gnome is said to be good, KDE doesnt show anything but works)

**Comment by iaacornus** [comment]
they are preinstalled in the system, from what i know in the initial setup when asking for password gnome ask whether to use password or fingerprint, although not sure since the fprint driver in my laptop is not supported by libfrint

```
>>> rpm -qa | grep print
libfprint-1.94.4-2.fc37.x86_64
fprintd-1.94.2-3.fc37.x86_64
fprintd-pam-1.94.2-3.fc37.x86_64
```

**Comment by trytomakeyouprivate** [comment]
I will install Kinoite on a machine with supported fingerprint soon. I am pretty sure GNOME works normally, I think KDE does not.

In general KDE has no start screen like GNOME, Gnomes anaconda (?) installer is absurdly tiny as all the rest is handled by gnome itself. 

So I guess the KDE approach would be to integrate setting up Fingerprint in the anaconda installer.

I think there is a GUI app for it, but of course its not elegant, we will see.

**Comment by trytomakeyouprivate** [comment]
fprint has a very nice GUI which handles all the commandline stuff. Really nice actually, maybe buggy, currently doesnt work

**Comment by iaacornus** [comment]
> I will install Kinoite on a machine with supported fingerprint soon. I am pretty sure GNOME works normally, I think KDE does not.
> 
> In general KDE has no start screen like GNOME, Gnomes anaconda (?) installer is absurdly tiny as all the rest is handled by gnome itself.
> 
> So I guess the KDE approach would be to integrate setting up Fingerprint in the anaconda installer.
> 
> I think there is a GUI app for it, but of course its not elegant, we will see.

apologies for the delayed response, my hands are full currently, although i would be able to join again soon. as for this, my machine with fingerprint does not work at all `lspic`, `lsusb` and others doesnt give any sensible output or even any indication of being able to read the device. Hence i think it depends on whether the device is supported, but as of now, theres barely hope in my case. although u can try if it would work in your machine

**Comment by iaacornus** [comment]
> fprint has a very nice GUI which handles all the commandline stuff. Really nice actually, maybe buggy, currently doesnt work

setting up fprint in cli should not be that much of a problem tho

**Comment by trytomakeyouprivate** [comment]
So I know one Acer laptop where fprint GUI seems to work but just crashes midterm. The KDE integration is perfect, it crashes in CLI too. And another one, Thinkpad with Synaptics Prometheus reader works perfectly. No cli needed
