### ISSUE TITLE
installation of recommended flatpaks

### ISSUE THREAD

**Issue by iaacornus** [iaacornus/Fedora-OSTree-Setup#7]
- [x] installation of recommended flatpak apps upon confirmation by user

**Comment by iaacornus** [comment]
lists of recommended flatpaks

```python
      "Mailspring": {
              "aid": "com.getmailspring.Mailspring",
              "simple_description": "A simple email client."
          },
      "LibreOffice": {
              "aid": "org.libreoffice.LibreOffice",
              "simple_description": "Office suite."
          },
      "VLC": {
              "aid": "org.videolan.VLC",
              "simple_description": "Video player."
          },
      "Okular": {
              "aid": "org.kde.okular",
              "simple_description": "A document viewer."
          },
      "GIMP": {
              "aid": "org.gimp.GIMP",
              "simple_description": "Photo editing application."
          },
      "ClamTk": {
              "aid": "com.gitlab.davem.ClamTk",
              "simple_description": "Front end for ClamAV."
          },
      "FlatSeal": {
              "aid": "com.github.tchx84.Flatseal",
              "simple_description": (
                      "GUI for managing flatpak"
                      " applications permission"
                  )
          }
```

**Comment by iaacornus** [comment]
@trytomakeyouprivate any other recommended flatpak apps you want to see?

**Comment by trytomakeyouprivate** [comment]
Mailspring looks nice! I thought it was closed-source, and the mailspring-ID and stuff are a bit irritating. I am not sure about the privacy of it, but Thunderbird is extremely outdated.

KeepassXC, Thunderbird, Firefox (or is it replaced anyways?)

```
 "KeepassXC": {
              "aid": "org.keepassxc.KeePassXC",
              "simple_description": "Secure Password manager."
          },
 "Cryptomator": {
              "aid": "org.cryptomator.Cryptomator",
              "simple_description": "Secure and easy encryption, especially for Cloud storages."
          },
 "Easy-Effects": {
              "aid": "com.github.wwmm.easyeffects",
              "simple_description": "Modify your PulseAudio sound"
          },
 "Sync-Thingy": {
              "aid": "com.github.zocker_160.SyncThingy",
              "simple_description": "Sync folders securely between devices, no server."
          },
 "XNView MP": {
              "aid": "com.xnview.XnViewMP",
              "simple_description": "Image Viewer and editor with many functions"
          },
 "Freetube": {
              "aid": "io.freetubeapp.FreeTube",
              "simple_description": "Watch YouTube privately with local subscriptions and playlists."
          },
 "Inkscape": {
              "aid": "org.inkscape.Inkscape",
              "simple_description": "A Vector graphics program"
          },
 "GNOME Boxen": {
              "aid": "org.gnome.Boxes",
              "simple_description": "Manage fast Virtual machines with a simple interface."
          },
 "Filelight": {
              "aid": "org.kde.filelight ",
              "simple_description": "View what files consume how much space in a pie chart."
          },
 "Kdenlive": {
              "aid": "org.kde.kdenlive",
              "simple_description": "Video cut program"
          },
 "Onion Share": {
              "aid": "org.onionshare.OnionShare",
              "simple_description": "Share files, chat and create websites over Tor"
          },
 "qBittorrent": {
              "aid": "org.qbittorrent.qBittorrent",
              "simple_description": "Share files decentral with a big community."
          },
 "Metadata-cleaner": {
              "aid": "fr.romainvigier.MetadataCleaner",
              "simple_description": "Easily remove all identifying information on Images using exiftool."
          },
```

**Comment by trytomakeyouprivate** [comment]
mailspring also seems to need "libsecret" installed. Maybe thats a Gnome thing?

**Comment by iaacornus** [comment]
> mailspring also seems to need "libsecret" installed. Maybe thats a Gnome thing?

I'm not sure, i have mailspring install but i dont see `libsecret`.

> It seems to be a big issue at the moment. Okay Thunderbird looks like shit now, it has a lot of buttons, but Mailspring just looks waaayy better. But until it doesnt run, I would only recommend it with a warning.

yeah it has more modern and simplistic ui, but perhaps lets also add thunderbird for some people

**Comment by trytomakeyouprivate** [comment]
so it seems that mailspring rpm works, the flatpak still has the problem accessing libsecret. I would not recommend installing the rpm really, as its from an external source. The same goes with the Flatpak actually, it is not as secure as for example Thunderbird from the repo or from Flathub. I actually use Betterbird, which is a softfork of Thunderbird, also available as Flatpak, I would recommend that as it seems to fix some stuff. 

Mailspring looks awesome, but all the nice features like link tracking (probably through a relay server) and even read notifications are pro, which is very expensive and afaik not FOSS. I would not recommend that at all. Also Mailspring has no support for PGP or SMIME at all, and probably will not have that for a while, why I uninstalled it again.

The UI may be more minimal than Thunderbird, and with "image loading off" it may reduce tracking, but Thunderbird is more privacy-friendly when tweaked and supports PGP veeery well with the recent updates fixing buttons etc.

I guess Mailspring Flatpak works on GNOME? It doesnt on various KDE distros, even though gnome-keyring and libsecret are installed. I did not get asked for a password though, so not actually a usability problem.

**Comment by trytomakeyouprivate** [comment]
I made configs for Thunderbird, we could automate that too maybe or at least download a README and arkenfox / "arkenbird"

**Comment by trytomakeyouprivate** [comment]
Firefox flatpak has some problems talking to the addons keepassxc-browser and kdeconnect

https://bugzilla.mozilla.org/show_bug.cgi?id=1621763

**Comment by trytomakeyouprivate** [comment]
This is a general Flatpak issue [Link](https://github.com/flatpak/xdg-desktop-portal/issues/283), we could use the workaround, but only if we also supply a "reverse-script", once the issue is resolved.

**Comment by trytomakeyouprivate** [comment]
actually I think Thunderbird is finally doing some really nice process, [Supernova update](https://www.techhut.tv/thunderbird-supernova-toots-gone-kde-update/), and it supports everything, RSS Feeds, Calendars, PGP.

**Comment by iaacornus** [comment]
> so it seems that mailspring rpm works, the flatpak still has the problem accessing libsecret. I would not recommend installing the rpm really, as its from an external source. The same goes with the Flatpak actually, it is not as secure as for example Thunderbird from the repo or from Flathub. I actually use Betterbird, which is a softfork of Thunderbird, also available as Flatpak, I would recommend that as it seems to fix some stuff.
> 
> Mailspring looks awesome, but all the nice features like link tracking (probably through a relay server) and even read notifications are pro, which is very expensive and afaik not FOSS. I would not recommend that at all. Also Mailspring has no support for PGP or SMIME at all, and probably will not have that for a while, why I uninstalled it again.
> 
> The UI may be more minimal than Thunderbird, and with "image loading off" it may reduce tracking, but Thunderbird is more privacy-friendly when tweaked and supports PGP veeery well with the recent updates fixing buttons etc.
> 
> I guess Mailspring Flatpak works on GNOME? It doesnt on various KDE distros, even though gnome-keyring and libsecret are installed. I did not get asked for a password though, so not actually a usability problem.

mailspring flatpak works perfectly fine in gnome, havent tried the functionality of gnome-keyring and libsecret yet, so I can't give a comment on this one, I'll look into it more. I also agree that installing it in rpm is not a good idea.

> I made configs for Thunderbird, we could automate that too maybe or at least download a README and arkenfox / "arkenbird"

Sure, can you create a better description of this in issues or in todo to track it since I'm not familiar with the description and the plans you have in mind.

> Firefox flatpak has some problems talking to the addons keepassxc-browser and kdeconnect
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1621763

yes, so i switched back to the default firepox rpm. I experienced more problem in flatpak firefox especially in video playbacks, it also seems to use more RAM and has problem in accessing files than the rpm firefox. I also noticed that its easier to deal with firefox rpm when working with files than the flatpak version.

**Comment by iaacornus** [comment]
the same mechanism with #13 , the user will be asked to input a number that corresponds to a specific application, then using that a command will be executed to install the selected applications by the user:

DEMO

![Screenshot from 2023-01-05 04-50-34](https://user-images.githubusercontent.com/96870156/210647677-2d3ce88b-e3e9-4133-8acc-a126600d8611.png)
